dist: trusty
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - QA
deploy:
  provider: heroku
  api_key:
    secure: YjV75AYwEwFvRuL4xPJE/5N+ts4Gqw3SdWF9bQuEyKpIJ23lmrV+y7867LH93Isb9iXPaCQ9fxjo/FEbsETgGXolVpb9Av862DhNFpkTuW4O/yfaFA/PI2znMFupYuzGu72KTdfds1WsdY5IIGWhTlGOimlaXFQCk0C3kE95ui1vaJR5TnK8KrNOiwDe2TIFg2zUR4IBqd5GUMIZJ4vHGZH/Kj18Hkja9WpMBPGvilsbNmsdOjRLkMUp1S5DtZOzkd6+h9BgmfgyPxRefASdNYwwXRxM7PKXlQsukVy1cmKga4hcSEbm6bwXCfxwSg0qnYdkzvQOLJ+Rwggtr8rkr5CeklumENgY3LanXlpLSVfeZv3mxdmr4xt2kLohIqbQJ0VpfmSnh7reBD/QILhs5NGhFAdJmNVolVKuA7qJgMRBAOatO6kypRToMqIcjeUH+e5u5IfVflwJ0QlYiKeIMMz6UENTioaOUQ7ftdKklsrkFz2uccoF9A6e0Trbe7w9+ar4KUTEKgAzDh2JusDq8sM4OWofO3EOqhGh0aIoJE7t5D4boDcAfgz8duAws09JuP6xtWKGnuFvvoI/xzBRZ5iIPCjFw+DfYSpicPYawByxRNYdQcSeKe/xhyNZrZPOcyEkgjJpXI9PxkVUYXNn5Ktn2ckkSyDD2vATGxySg80=
  app: iframex
  on:
    repo: baab-bee/AngularRepo
    branch: QA
