dist: trusty
language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - QA
deploy:
 - provider: heroku
   app: iframex
   api_key:
     secure: eFiBwNJPYyoXvX9+2gd2VMEJ9MrtcS8Xv4GXHHWJb2fMMRvaFO/1oCwlWJMf07gFQxJ+Uk37M+VMfGQOAfqoXtePJaH+1Pz0HYnX509HCg91GFFsGOJfpQ0Qc1QbJ5CrCv48TjrQYUP+KE22hwoOPY2wU+MuU68wqBH6dEw3dsN+a5tStcBMgIze5ygPZzBqEm+otRzteY8cNT8H/9fU98haV9ULznjMIPsCimlD4UjKi0vw/gCZyThn7mQY0KND9hLQBrro06dx/0j+I3YHoXwSq5hzQuUonJV9oenQtgfKztQk7R3vwl+ii7NT1RCOWFSUs2/T94TAISoHPiaaGC13pjBbLEHjqhtprQ0OGiuddETeSWZ2ke8vQC37CFUGDDAaN3F9TAOVmuj0l+QiHNe2QniFvqi6BljIggdOxTCgeyP2NXspGlvI4ucLxXjkliw1gbiqaxU6cf88Ak6XiT0dAe6E/gVo5C6ulcVBMii2e0npTkUUJWd7JpECVxWVuY8JFpniyqsWbuGBXM4o8MNpTrABdpK4z5+Zv08W2fH1qh2EBfiTz1PGhj9uelEyfyuVoceHLg7IItZfaq0bX3dUIWKs/ngLV3E2z5qYGpbtLBIhZsFOxZ7qY5V56N9WxKF6vibVubGdhz0j6rXCQUY3dIHX0puw4f1+yT6+8zo=
   on:
     branch: QA