dist: trusty
language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - QA
deploy:
- provider: heroku
  app: iframex
  api_key:
    secure: SoI7hcwA6MwlpzEOxh4X67JqDhcDodffx8dZ5vplnEV4VV6eg4jS2yJaQOP2jiDhjHzdESjApRbsAb6FLLJ85pZ+fEogl4dRX903VsBsxs2sMihzKlUnV8saG89ygSejFxhlP7lFhga1YrOxPDhVfeZdu1Xosru+mAsTpi0IYxdT08d30Li0qWhJ5KnTcBC2Ul/wtU5oDW7e/zAnwbqmt0mf1NbNZEm79eEW/2mOEq49HbXC5qWDjjiqdjRZcQMenWpM3HDpRCizNYQZ28OfE6iZgp1grCmLU5r3eg9HtUIRULn/TcgRlSt8owG2sp3om19pGUVmq6h+KSaXkB5KPzJQ7JJEt28UeYrBal3h6EYwN4MJ2CZYR4Ltz3gHe8VbqVvZYxB4GXpFWsCbZ4N8BlGfHh31Oo0S7AF6EEU2Zo5TOgfS15ZeeABSt7MJIHvtD5aaeXOe5nAlwDPpz7wcgQXMRsytUgJRVRbYm/SJVrEWQeOq7X6eXjNiW0O7cMVCebyMd0liQ+2HYnfrjleC+oR6xxsdB14NIZQoJSCn8fgGloUULCU0LeV8ekpV1g0s6PPCUOTrf3+2VHExgQQe2jaWsxS35JGHOcfcaEAX4frU7uFTGqKIHYkfqBBx38GAdPStNd8iu4WPxdU42iSI/iw6lzHZ0UzsldzRwT8NiWA=
  on:
    branch: QA